# ------------------------------ #
# --- PROJECT ------------------ #
# ------------------------------ #

[project]
name = "job-crawler"
version = "0.1.0"
description = "Community crawler for job postings."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.9",
]


# ------------------------------ #
# --- RUFF --------------------- #
# ------------------------------ #

[tool.ruff]

# Files to include in the check.
include = [
    "pyproject.toml",
    "job-crawler/**/*.py",
	"tests/**/*.py"
]
exclude = []

# 
line-length = 128
indent-width = 4
target-version = "py312"
cache-dir = ".cache/ruff"

# --- LINT --------------------- #

[tool.ruff.lint]

# Rules selection
select = ["ALL"]
ignore = [
    
    # Flake8-annotations (ANN)
    "ANN002",   # Missing type annotation for *{name}
    "ANN003",   # Missing type annotation for **{name}

    # Warning (W)
    "W191",     # Indentation contains tabs

    # Pydocstyle (D)
    "D203",     # 1 blank line required before class docstring
    "D206",     # Docstring should be indented with spaces, not tabs
    "D213",     # Multi-line docstring summary should start at the second line
    "D407",     # Missing dashed underline after section ("{name}")
    "D408",     # Section underline should be in the line following the section's name ("{name}")

]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# --- FORMAT ------------------- #

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"